# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Miyamoto_Next_config = debug

else ifeq ($(config),release)
  Miyamoto_Next_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Miyamoto-Next

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Miyamoto-Next:
ifneq (,$(Miyamoto_Next_config))
	@echo "==== Building Miyamoto-Next ($(Miyamoto_Next_config)) ===="
	@${MAKE} --no-print-directory -C . -f Miyamoto-Next.make config=$(Miyamoto_Next_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Miyamoto-Next.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Miyamoto-Next"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"